base_url = "https://ics.upjs.sk/~novotnyr/home/skola/konkurentne-programovanie/portal"
title = "UINF/KOPR Konkurentné programovanie"
compile_sass = true
build_search_index = false
theme = "Zulma"

[markdown]
highlight_code = true

[extra]
zulma_title = "UINF/KOPR Konkurentné programovanie"
